spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:mysql://fitness.ceediucewee4.ap-northeast-2.rds.amazonaws.com:3306/fitness
    username: admin
    password: qkrwlgns98!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true